### ISSUE TITLE
Mejoras zoom

### ISSUE THREAD

**Issue by jvillegas88** [JChambu/geoworks#863]
Las mejoras incluyen:

- [ ] Mantener la posición del zoom al cambiar de proyecto
- [ ] Hacer zoom a las geometrías luego de modificar la selección (ej luego de aplicar un filtro)
- [ ] Permitir zoom más cercano
